name: Terraform_plan

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    name: tf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terrafrom validate -no-color