name: Terraform Validate and Plan  ### Github actions workflow for Validating and planning the TF for aws infrastructure

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-validate:
    name: TF plan dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  ### Refer to repository for secret key id and access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Configure Backend with Existing S3 Bucket
      run: |
        
        S3_BUCKET_NAME="terraform-state-s3-yv"   ### Replace <your-existing-s3-bucket-name> with your actual S3 bucket name

        # Configure AWS CLI with the provided credentials and S3 bucket name
        
        aws configure set aws-access-key-id $AWS_ACCESS_KEY_ID
        aws configure set aws-secret-access-key $AWS_SECRET_ACCESS_KEY
        aws configure set region us-east-1  # Change this to your desired AWS region
        aws configure set preview.cloudfront true

        # Initialize Terraform with the existing S3 bucket as the backend
        
        terraform init -backend-config="bucket=$S3_BUCKET_NAME"

    
        terraform validate    ### Validate Terraform configuration
      working-directory: setting_up_Redis_cluster

    - name: Terraform plan       #### Lists the resources that will be created on AWS Cloud Platform
      run: terraform plan -out=tfplan
      working-directory: setting_up_Redis_cluster