name: Verify Feature     ### Name of the workflow

on:
  pull_request:
    branches:  ### working Branch name / main/ master branch
      - tf-working-branch
  workflow_dispatch:


jobs:
  terraform_plan:
    name: TF plan dev
    runs-on: ubuntu-latest

    env:
      TF_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_aws_default_region: "us-east-1"
      TF_BACKEND_CONFIG: "s3://terraform-s3-state-yv/"

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7


      - name: Initialize Terraform
        run: |
          terraform init -backend-config="${{ env.TF_BACKEND_CONFIG }}"
        working-directory: aws-infrastructure

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: aws-infrastructure

      - name: Terraform plan       #### Lists the resources that will be created on AWS Cloud Platform 
        run: terraform plan -out=tfplan
        working-directory: aws-infrastructure
      
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: aws-infrastructure