name: Verify Feature

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
env: 
  WORKING-DIR: Terraform

jobs:
  terraform_plan:
    name: TF plan dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./${{ env.WORKING_DIR }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: install
        env:
          TF_VERSION: "1.6.1"
        run: terraform version
      
      - name: Terraform init
        id: init
        run: terraform init
